export const restaurantsData = [
	{
		"address": "2-14 Cliff Rd, North Wollongong NSW 2500",
		"close_time": "6:00 PM",
		"cuisine": "CAFE",
		"distance": "5 KM",
		"expected_delivery_time": "10-15 Min",
		"id": 2,
		"image_url": "https://lh3.googleusercontent.com/p/AF1QipMQwlvcpHrovFyDgYw5njediImT7zekO1iKLKGk=s1360-w1360-h1020",
		"mobile": "0423859543",
		"name": "Pepe On The Beach",
		"offers": "Free food delivery",
		"open_time": "10:00 AM",
		"rating": 3.0,
		"reviews": "Great place to chill, nice tacos, friendly staffs especially Paige, she was so helpful. The best thing is the view. Happy hour is worthed."
	},
	{
		"address": "18 Cliff Rd, Wollongong, New South Wales 2500 Australia",
		"close_time": "10:00 PM",
		"cuisine": "CAFE",
		"distance": "20 KM",
		"expected_delivery_time": "30-45 Min",
		"id": 4,
		"image_url": "https://tse3.mm.bing.net/th?id=OIP.0yL5WUD3cgenzUtl2_tKeQHaFj&pid=Api&P=0&h=180",
		"mobile": "0422928225",
		"name": "Diggies",
		"offers": "Free food delivery",
		"open_time": "9:00 AM",
		"rating": 5.0,
		"reviews": "But, the food could be better. I have been here on multiple occasions and still haven’t found something to eat that I want to go back for."
	},
	{
		"address": "16 Cliff Rd, Wollongong, New South Wales 2500 Australia",
		"close_time": "8:00 PM",
		"cuisine": "CAFE",
		"distance": "15 KM",
		"expected_delivery_time": "20-25 Min",
		"id": 5,
		"image_url": "https://tse1.mm.bing.net/th?id=OIP.BC2fuM_1c1xtnu4HvAWAaAHaE7&pid=Api&rs=1&c=1&qlt=95&w=173&h=115",
		"mobile": "0422816543",
		"name": "Connies Cliff Rd Cafe",
		"offers": "Free food delivery",
		"open_time": "6:00 AM",
		"rating": 1.0,
		"reviews": "Beautiful seaside location, delicious food presented well and friendly, efficient service. Excellent gluten free options, and plenty to choose from. Easy to recommend and would very happily dine again."
	},
	{
		"address": "2-14 Cliff Rd, Wollongong, New South Wales 2500 Australia",
		"close_time": "12:00 PM",
		"cuisine": "BAR",
		"distance": "10 KM",
		"expected_delivery_time": "15-20 Min",
		"id": 6,
		"image_url": "https://media-cdn.tripadvisor.com/media/photo-s/1c/ef/3b/ff/palisade-booth-seating.jpg",
		"mobile": "0422431234",
		"name": "Palisade Kitchen & Bar",
		"offers": "Free food delivery",
		"open_time": "5:00 PM",
		"rating": 2.0,
		"reviews": "The food was superb, stands out from a lot of the other Indian restaurants in the area. The use of whole spices and meat on the bone (we had the goat biryani and goat rara) added so much depth of flavour. Housemade kulfi was absolutely delicious."
	},
	{
		"address": "18 Cliff road, Wollongong, New South Wales 2500 Australia",
		"close_time": "6:00 PM",
		"cuisine": "RESTAURANT",
		"distance": "5 KM",
		"expected_delivery_time": "10-15 Min",
		"id": 7,
		"image_url": "https://tse1.mm.bing.net/th?id=OIP.uf-bW7rzFy1EzGHDevOR5QAAAA&pid=Api&rs=1&c=1&qlt=95&w=93&h=93",
		"mobile": "0456431257",
		"name": "Seaside Shahi",
		"offers": "Free food delivery",
		"open_time": "10:00 AM",
		"rating": 2.0,
		"reviews": "everything about this place was absolutely immaculate. The service was incredible but not as much as the food. The onion bhaji really was the best thing i have ever tasted."
	},
	{
		"address": "54-58 Cliff Rd, Wollongong, New South Wales 2500 Australia",
		"close_time": "6:00 PM",
		"cuisine": "RESTAURANT",
		"distance": "15 KM",
		"expected_delivery_time": "20-25 Min",
		"id": 8,
		"image_url": "https://media-cdn.tripadvisor.com/media/photo-s/1a/b2/cc/86/img20200122102441-largejpg.jpg",
		"mobile": "0433314443",
		"name": "Blu Orange",
		"offers": "Free food delivery",
		"open_time": "10:00 AM",
		"rating": 4.0,
		"reviews": "Food is mediocre and over priced, no table service and the service itself is slow. Had sold out of chips on a Sunday afternoon. Much better options close by."
	},
	{
		"address": "2/293-297 Crown St, Wollongong NSW 2500",
		"close_time": "7:00 PM",
		"cuisine": "RESTAURANT",
		"distance": "5 KM",
		"expected_delivery_time": "10-15 Min",
		"id": 9,
		"image_url": "https://lh3.googleusercontent.com/p/AF1QipNA7wFJnr3o9ZHmhvXpUiYcZ2kMtzGF08BASN26=s1360-w1360-h1020",
		"mobile": "0427771334",
		"name": "star venus",
		"offers": "Free food delivery",
		"open_time": "10:00 AM",
		"rating": 4.0,
		"reviews": "Extremely greasy food, did not have half the food available and tried to avoid making a product that was paid for. Service was rude and staff seem unorganised. Prices are unreasonable for the food provided. A giant cockroach was also in the middle of the floor while waiting. Would not recommend"
	},
	{
		"address": "121 Keira St, Wollongong NSW 2500",
		"close_time": "1:00 AM",
		"cuisine": "BAR",
		"distance": "10 KM",
		"expected_delivery_time": "15-20 Min",
		"id": 10,
		"image_url": "https://lh3.googleusercontent.com/p/AF1QipM9XQKE7pZj18etET1efOiadcTVBdm--CpcEmme=s1360-w1360-h1020",
		"mobile": "0433214643",
		"name": "Juniper Bar",
		"offers": "Free food delivery",
		"open_time": "5:00 PM",
		"rating": 5.0,
		"reviews": "Cute gin bar with a romantic vibe. Candles on the tables low lighting at night. Cocktails are delicious. Friendly staff. We went at about 8pm on a Saturday and some tables were still available. Outside area for smokers."
	},
	{
		"address": "19 Cliff road, Wollongong, New South Wales 2500 Australia",
		"close_time": "7:00 PM",
		"cuisine": "RESTAURANT",
		"distance": "15 KM",
		"expected_delivery_time": "20-25 Min",
		"id": 12,
		"image_url": "https://lh3.googleusercontent.com/p/AF1QipNkG4Sk0Tu87YrKQQqCZ5I5mW0XjQ8GBT0mrcll=s1360-w1360-h1020",
		"mobile": "0450431257",
		"name": "aria",
		"offers": "Free food delivery",
		"open_time": "10:00 AM",
		"rating": 3.0,
		"reviews": "Food is mediocre and over priced, no table service and the service itself is slow. Had sold out of chips on a Sunday afternoon. Much better options close by."
	},
	{
		"address": "2/14 Cliff Rd, North Wollongong NSW 2500",
		"close_time": "5:00 PM",
		"cuisine": "CAFE",
		"distance": "5 KM",
		"expected_delivery_time": "10-15 Min",
		"id": 13,
		"image_url": "https://lh3.googleusercontent.com/p/AF1QipNwD1c1fI1w9e48Mz0-yElQBdtVqTE00zMf6Od9=s1360-w1360-h1020",
		"mobile": "0433224443",
		"name": "Picolo Kitchen & Bar",
		"offers": "Free food delivery",
		"open_time": "9:00 AM",
		"rating": 3.0,
		"reviews": "We enjoyed breakfast very much sitting next to the window and looked at the beautiful North Beach. Food was fine for a buffet breakfast."
	},
	{
		"address": "3/123 Corrimal St, Wollongong NSW 2500",
		"close_time": "7:00 PM",
		"cuisine": "RESTAURANT",
		"distance": "5 KM",
		"expected_delivery_time": "10-15 Min",
		"id": 14,
		"image_url": "https://lh3.googleusercontent.com/p/AF1QipMsVfEZ-QAbw4oqu_ctzo1Ike6bIEeXCC9NHfsF=s1360-w1360-h1020",
		"mobile": "0400981994",
		"name": "Levant Restaurant",
		"offers": "Free food delivery",
		"open_time": "10:00 AM",
		"rating": 4.0,
		"reviews": "Beautiful seaside location, delicious food presented well and friendly, efficient service. Excellent gluten free options, and plenty to choose from. Easy to recommend and would very happily dine again."
	},
	{
		"address": "SHOP 19 /110/114 Crown St, Wollongong NSW 2500",
		"close_time": "2:00 AM",
		"cuisine": "BAR",
		"distance": "10 KM",
		"expected_delivery_time": "15-20 Min",
		"id": 15,
		"image_url": "https://lh3.googleusercontent.com/p/AF1QipNEZhBc3eMYtnqRVe6Qag-JDHPLn4ZmkYJjKNhO=s1360-w1360-h1020",
		"mobile": "0407881888",
		"name": "Lux Bistro Bar",
		"offers": "Free food delivery",
		"open_time": "5:00 PM",
		"rating": 4.0,
		"reviews": "Went during the Easter long weekend and although we knew a surcharge was going to be added didn’t know it would be 20% of the bill… bit steep I thought. But the service was worth it"
	},
	{
		"address": "60/62 Harbour St, Wollongong NSW 2500",
		"close_time": "9:00 PM",
		"cuisine": "RESTAURANT",
		"distance": "10 KM",
		"expected_delivery_time": "15-20 Min",
		"id": 16,
		"image_url": "https://lh5.googleusercontent.com/p/AF1QipOfLhozM6CgpfxsborXaZVcWR4FGAFbmclzf1WF=w260-h175-n-k-no",
		"mobile": "0450961257",
		"name": "Coldwater Creek",
		"offers": "Free food delivery",
		"open_time": "11:00 AM",
		"rating": 5.0,
		"reviews": "Nice quiet spot. The food was delicious, although serving sizes and hence value for money left a bit to be desired."
	},
	{
		"address": "7 Globe Ln, Wollongong NSW 2500",
		"close_time": "2:00 AM",
		"cuisine": "BAR",
		"distance": "5 KM",
		"expected_delivery_time": "10-15 Min",
		"id": 11,
		"image_url": "https://lh5.googleusercontent.com/p/AF1QipPQKslhrr4HO90z7FsSFj6n-5QyJpSHkyQ_MGd3=w260-h175-n-k-no",
		"mobile": "0407881304",
		"name": "Bevanda Bar",
		"offers": "Free food delivery",
		"open_time": "6:00 PM",
		"rating": 5.0,
		"reviews": "Billie was great, we had a friend with a medical emergency and she treated her with so much care. Baz the security guard was also so amazing in being patient. Such great client care, patience while managing a busy place. Thankyou so much they deserve a bonus."
	},
	{
		"address": "5 Cliff Rd North Wollongong, Wollongong, New South Wales 2500 Australia",
		"close_time": "6:00 PM",
		"cuisine": "RESTAURANT",
		"distance": "15 KM",
		"expected_delivery_time": "20-25 Min",
		"id": 3,
		"image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSZQImiVeNZ5quhqUAZd0sS_Q-DzXbm3wnJg&s",
		"mobile": "0429459282",
		"name": "North Beach Pavilion",
		"offers": "Free food delivery",
		"open_time": "10:00 AM",
		"rating": 4.0,
		"reviews": "The place is amazing! It’s got one of the best ambience in all of Wollongong."
	},
	{
		"address": "7/21 Globe Ln, Wollongong NSW 2500",
		"close_time": "9:00 PM",
		"cuisine": "RESTAURANT",
		"distance": "10 KM",
		"expected_delivery_time": "15-20 Min",
		"id": 17,
		"image_url": "https://imgix.theurbanlist.com/content/article/best-indian-restaurants-melbourne-3.png",
		"mobile": "0450111111",
		"name": "Indian Restaurant",
		"offers": "Free food delivery",
		"open_time": "11:00 AM",
		"rating": 4.0,
		"reviews": "Beautiful seaside location, delicious food presented well and friendly, efficient service. Excellent gluten free options, and plenty to choose from. Easy to recommend and would very happily dine again."
	},
	{
		"address": "337 Crown Street, Wollongong NSW 2500",
		"close_time": "3:00 PM",
		"cuisine": "CAFE",
		"distance": "5 KM",
		"expected_delivery_time": "10-15 Min",
		"id": 19,
		"image_url": "https://lh3.googleusercontent.com/p/AF1QipNygkyTvm712DsRPi5Ut1Iz-mRaUdUuy2YpWwHZ=s1360-w1360-h1020",
		"mobile": "0498234521",
		"name": "Lettuce B Frank",
		"offers": "Free food delivery",
		"open_time": "6:00 AM",
		"rating": 5.0,
		"reviews": "Yummy and healthy food with great service and chilled vibes."
	},
	{
		"address": "Shop 4/19/21 Princess Highway, Fairy Meadow NSW 2519",
		"close_time": "3:30 PM",
		"cuisine": "CAFE",
		"distance": "10 KM",
		"expected_delivery_time": "20-25 Min",
		"id": 20,
		"image_url": "https://i1.au.reastatic.net/768x512-smart=75,r=33,g=40,b=46,quality=60,progressive/bdb0526e0dda93975707a96f0c273472c02e9411b26be30320847d68fb108327/image2.jpg",
		"mobile": "0423128554",
		"name": "Xavier place",
		"offers": "Free food delivery",
		"open_time": "5:30 AM",
		"rating": 5.0,
		"reviews": "The staff and owner are the nicest and the food is really tasty."
	},
	{
		"address": "87 Crown Street, Wollongong NSW 2500",
		"close_time": "2:00 PM",
		"cuisine": "CAFE",
		"distance": "5 KM",
		"expected_delivery_time": "15-20 MIN",
		"id": 21,
		"image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSZQImiVeNZ5quhqUAZd0sS_Q-DzXbm3wnJg&s",
		"mobile": "0421678723",
		"name": "Lee and Me",
		"offers": "Free food delivery",
		"open_time": "6:00 AM",
		"rating": 4.0,
		"reviews": "Tasty campos coffee and great food with a good variety for breakfast options."
	},
	{
		"address": "5 Crown Ln, Wollongong NSW 2500",
		"close_time": "9.30PM",
		"cuisine": "BAR",
		"distance": "3KM",
		"expected_delivery_time": "5-7 MinMin",
		"id": 22,
		"image_url": "https://lh3.googleusercontent.com/p/AF1QipPyOrAcGOkLbFYODb30GzmCwrUplAKDQwNa3oIh=s1360-w1360-h1020",
		"mobile": "0242297829",
		"name": "Kneading Ruby",
		"offers": "Free food delivery",
		"open_time": "5:00 PM",
		"rating": 4.0,
		"reviews": "Kneading Ruby in Wollongong exceeded all expectations! From the moment we walked in, we were greeted with warmth and hospitality. The Italian food was absolutely amazing"
	},
	{
		"address": "The Strand, 17/54-58 Cliff Rd, Wollongong NSW 2500",
		"close_time": "9:00 PM",
		"cuisine": "RESTAURANT",
		"distance": "3.9KM",
		"expected_delivery_time": "7-10 Min",
		"id": 23,
		"image_url": "https://lh5.googleusercontent.com/p/AF1QipMOZSOZ2hCpnlGxziBReQiQgt_QbsERHu7fZMDs=w130-h87-n-k-no",
		"mobile": "0242259888",
		"name": "Aqua Restaurant",
		"offers": "Free food delivery",
		"open_time": "7:30 AM",
		"rating": 4.0,
		"reviews": "We recently had lunch at Aqua and had a fantastic experience! The bruschetta was a delightful starter, and both the fish and chips and the salmon were outstanding. The atmosphere was lovely, and the overall dining experience was excellent. Highly recommend this place!"
	},
	{
		"address": "22 corner of Market and, Corrimal St, Wollongong NSW 2500",
		"close_time": "9:00 PM",
		"cuisine": "RESTAURANT",
		"distance": "3.9KM",
		"expected_delivery_time": "7-10 Min ",
		"id": 24,
		"image_url": "https://lh5.googleusercontent.com/p/AF1QipO6HrwgJ_zCWo3JXEgskRflj6bo_TqAoP4c5nzY=w260-h175-n-k-no",
		"mobile": "0242296950",
		"name": "Samaras Restaurant",
		"offers": "Free food delivery",
		"open_time": "11:00 AM",
		"rating": 5.0,
		"reviews": "Good food. Generous portion size good atmosphere. Place was really noisy but thats because it was really busy. booking is essential."
	},
	{
		"address": "52/54 Crown St, Wollongong NSW 2500",
		"close_time": "9:30 PM",
		"cuisine": "RESTAURANT",
		"distance": "4KM",
		"expected_delivery_time": "7-9 Min",
		"id": 25,
		"image_url": "https://lh5.googleusercontent.com/p/AF1QipNjArek2kqjcj0x9E0UKIXUOT8hB9GyJQ1IH08h=w260-h175-n-k-no",
		"mobile": "0242250481",
		"name": "Asees Restaurtant",
		"offers": "Free food delivery",
		"open_time": "12:00 PM",
		"rating": 4.0,
		"reviews": "I recently had a fantastic meal at this restaurant the food was delicious and beautifully presented. The service was also excellent and the ambiance was cozy and inviting. I normally go there for traditional Indian dishes especially a must try dish in a menu the Prawn masala and fry Fish"
	},
	{
		"address": "Shop 4/166 Keira St, Wollongong NSW 2500",
		"close_time": "1:00 AM",
		"cuisine": "BAR",
		"distance": "3.1 KM",
		"expected_delivery_time": "8-10 Min",
		"id": 28,
		"image_url": "https://resizer.otstatic.com/v2/photos/xlarge/3/57135530.webp",
		"mobile": "0412692675",
		"name": "Roy Resto Bar",
		"offers": "Free food delivery",
		"open_time": "11:00 AM",
		"rating": 4.9,
		"reviews": "Incredible new venue in Wollongong, exactly what was needed in the CBD. Exciting and funky menu that was executed perfectly. Everything was top notc"
	},
	{
		"address": "2/88 Kembla St, Wollongong NSW 2500",
		"close_time": "11:00 PM",
		"cuisine": "BAR",
		"distance": "3.8 KM",
		"expected_delivery_time": "7 - 9 Min",
		"id": 29,
		"image_url": "https://lh3.googleusercontent.com/p/AF1QipOrF_r-eHe7OvYrIuT-OowYwVMJeuhE6T3x8tos=s1360-w1360-h1020",
		"mobile": "0432220300",
		"name": "Mia Mia",
		"offers": "Free food delivery",
		"open_time": "4:00 PM",
		"rating": 4.5,
		"reviews": "Awesome wine list with wide selection of good wines by the glass and great bottle selection with Italian greats. "
	},
	{
		"address": "The Strand, 17/54-58 Cliff Rd, Wollongong NSW 2500",
		"close_time": "9:00 PM",
		"cuisine": "RESTAURANT",
		"distance": "3.9 KM",
		"expected_delivery_time": "10-12 Min",
		"id": 30,
		"image_url": "https://lh5.googleusercontent.com/p/AF1QipPFWQW1qH4ASh_Ud1JXcWS46ynRXqqe7j1zeYE-=w260-h175-n-k-no",
		"mobile": "0242259888",
		"name": "Hubert Restaurant",
		"offers": "Free food delivery",
		"open_time": "7:30 AM",
		"rating": 3.9,
		"reviews": "Food was mid. Nothing special compared to the price. Terrible service"
	},
	{
		"address": "1/220 Keira St, Wollongong NSW 2500",
		"close_time": "8:00 PM",
		"cuisine": "RESTAURANT",
		"distance": "8 KM",
		"expected_delivery_time": "12-15 Min",
		"id": 31,
		"image_url": "https://lh3.googleusercontent.com/p/AF1QipOkelqvMgNh27CeNXyujFT85CzYorwMQqwdUrUa=s1360-w1360-h1020",
		"mobile": "0432132777",
		"name": "Bento house Japanese",
		"offers": "Free food delivery",
		"open_time": "11:00 AM",
		"rating": 4.0,
		"reviews": "The service and hot food was great! But the sushi was very dry and not delicious"
	},
	{
		"address": "3/50 Crown St, Wollongong NSW 2500",
		"close_time": "9:30 PM",
		"cuisine": "RESTAURANT",
		"distance": "4KM",
		"expected_delivery_time": "8-11 Min",
		"id": 1,
		"image_url": "https://lh5.googleusercontent.com/p/AF1QipPV5bGa_9BWOeOcqR64zmEjH0rwMylakUH1KK8Y=w260-h175-n-k-no",
		"mobile": "0242250889",
		"name": "JJs Indian Restaurant",
		"offers": "Free food delivery",
		"open_time": "12:00 PM",
		"rating": 5.0,
		"reviews": "Thoroughly enjoyed the butter chicken, lamb and beef curries. Crisp naan bread, spicy biryanis. Fast service with food coming out very quickly. Authentic flavours and spicy hot - so mention to the lovely staff if you prefer more mild heat. Recommend. Teenagers loved it."
	},
	{
		"address": "21 Osborne street, Wollongong, NSW 2500",
		"close_time": "11:00 PM",
		"cuisine": "BAR",
		"distance": "2.9KM",
		"expected_delivery_time": "6-10 Min",
		"id": 27,
		"image_url": "https://lh3.googleusercontent.com/p/AF1QipNAx80DxlT-4uHiORpdoXEIZs1F_S86Sj5O0iNW=s1360-w1360-h1020",
		"mobile": "0292479777",
		"name": "Northern O Bar",
		"offers": "Free food delivery",
		"open_time": "12:00 PM",
		"rating": 3.8,
		"reviews": "Relaxing atmosphere, good service, and really cool and comfortable seating"
	},
	{
		"address": "3 Verekar Street, Wollongong 2510",
		"close_time": "3:00 PM",
		"cuisine": "CAFE",
		"distance": "5 KM",
		"expected_delivery_time": "10-15 Min",
		"id": 18,
		"image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSZQImiVeNZ5quhqUAZd0sS_Q-DzXbm3wnJg&s",
		"mobile": "0442884204",
		"name": "Evil Eye Cafe",
		"offers": "Free food delivery",
		"open_time": "6:00 AM",
		"rating": 5.0,
		"reviews": "Very reasonably priced, chana dal is really nice same with the garlic naan. Always friendly too!"
	}
];