name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies and build
        working-directory: delivery-app
        run: |
          rm -rf node_modules
          rm -rf package-lock.json
          npm install
          npm install -g react-scripts
          npm install eslint eslint-plugin-react-hooks --save-dev
          npm run build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Test
        working-directory: delivery-app
        run: |
          rm -rf node_modules
          rm -rf package-lock.json
          npm install
          npm install -g react-scripts
          npm test -- -u
          
